sudo: required

language: node_js

node_js:
  - "10"
  - "8"

before_script:
  - npm install -g @angular/cli

script:
  - npm run build
  - npm run lint
  - npm run stylelint
  - npm run test:coverage